# `Práctica 7 Pandas`

> Añadir blockquote

> Añadir blockquote

## Biblioteca Pandas

## Introducción

* Las filas y columnas están identificados con etiquetas, además de simples índices enteros
* Es importante entender un poco de las estructuras de Pandas
* Tres estructuras importantes:
    + `Series`
    + `DataFrame`
    + `Index`

In [1]:
import numpy as np
import pandas as pd

## Objetos `Series` en Pandas

* Puede pensarse como una array de una sola dimensión indexado.
* Puede ser creado desde una lista:

In [2]:
edades = [1,4,5,6,17,87]
pandeado = pd.Series(edades)
pandeado
print(pandeado)

0     1
1     4
2     5
3     6
4    17
5    87
dtype: int64

* Una ``Series`` encapsula tanto una secuencia de valores como una de índices.
* Podemos acceder a ellos con los atributos `values` e `index`

In [3]:
pandeado.values

array([ 1,  4,  5,  6, 17, 87])

* Un `index` es un objeto similar a un array.

In [4]:
pandeado.index

RangeIndex(start=0, stop=6, step=1)

* Podemos acceder a una `Series` a través del índice asociado de forma similar a los arrays de Numpy: con los `[]`

In [5]:
pandeado[3]

np.int64(6)

In [6]:
print(pandeado[2])

5

### ``Series`` como generalización de un array de  NumPy

* La diferencia esencial con un array de Numpy es que mientras que el array tiene un índice entero *"implícitamente definido"*, una `Series` de Pandas tiene un índice asociado a los valores *que está definido de forma explícita*
* Este índice explícito le da a una `Series` capacidades adicionales.
* El índice explícito no tiene por qué ser un entero y tampoco todos sus valores tienen que ser necesariamente únicos.

* Pueden ser `strings`

In [7]:
dias = pd.Series([1,2,3,4,5],
                 index=["Lunes", "Martes", "Miercoles", "Jueves", "Viernes"])
dias

Lunes        1
Martes       2
Miercoles    3
Jueves       4
Viernes      5
dtype: int64

In [8]:
dias.index

Index(['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes'], dtype='str')

* Y podemos acceder simplemente:

In [9]:
dias["Miercoles"]

np.int64(3)

* O puede ser una secuencia no contigua de `int`s

In [10]:
intts = pd.Series([1, 15, 2, 30],
                  index=[8, 3, 14, 2])
intts

8      1
3     15
14     2
2     30
dtype: int64

In [11]:
print("Por clave: ", intts[2])
print("Por posicion: ", intts.iloc[2])

Por clave:  30
Por posicion:  2

### ``Series`` como un `dict` especializado

* Un `dict` es una estructura que mapea un set de keys arbitrarias a un set de valores de un tipo.
* Puede hacerse, entonces, una analogía entre una `Series` y un `dict`

In [12]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
# population_dict
populationn = pd.Series(population_dict)
populationn

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [13]:
# population_dict.values()
populationn.values

array([38332521, 26448193, 19651127, 19552860, 12882135])

In [14]:
# population_dict.keys()
populationn.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='str')

* Puede crearse una `Series` a partir de un `dict`: el índice se toma de las keys.
* Así, puede accederse de forma análoga a un `dict`.

In [15]:
populationn["Texas"]

np.int64(26448193)

* A diferencia de un `dict` una `Series` soporta algunas operaciones del estilo de un array, como por ejemplo, slicing:

In [16]:
populationn["New York":"Illinois"]

New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

* Si creamos una `Series` con una lista de strings se respeta el orden de las columnas, mientras que las claves de los `dicts` se ordenan alfabéticamente al crearse la `Series`

In [17]:
estados_list = ['Illinois','Texas','New York', 'Florida', 'California']
estados_pop = [12882135, 26448193, 19651127, 19552860, 38332521]
estados = pd.Series(estados_pop, index= estados_list)

In [18]:
estados['New York':'California']

New York      19651127
Florida       19552860
California    38332521
dtype: int64

### Construyendo objetos Series

* Podemos construir `Series` desde cero. La forma general de hacerlo es la siguiente:

```python
>>> pd.Series(data, index=index)
```
* `index` es un argumento opcional y `data` puede ser varias cosas

In [19]:
# Una lista o un array de Numpy
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [20]:
# Un escalar repetido a lo largo de un índice
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [21]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: str

In [22]:
# En cada caso, podría usarse el índice explícitamente si lo que se busca es otro resultado
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: str

## Objeto `DataFrame`

* Otra estructura fundamental.
* También puede ser pensada como una generalización de un array de NumPy o como un tipo especial de diccionario.

### `DataFrame` como un array de Numpy

* Un `DataFrame` es un tipo análogo a una `Series` en dos dimensiones y, por lo tanto, puede ser una pensado tanto como una generalización de un array de Numpy o como un conjunto de `Series` alineados. Es decir, que tienen el mismo índice.

* Para demostrar esto generemos una `Serie` con el área de algunos estados:

In [23]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': np.nan}
area = pd.Series(area_dict)
area

California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois           NaN
dtype: float64

In [24]:
populationn

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

* Ahora, podemos usar un diccionario para construir un objeto bidimensional conteniendo toda la información.

In [25]:
estados = pd.DataFrame({'population': populationn,
                        'area': area})
estados

            population      area
California    38332521  423967.0
Texas         26448193  695662.0
New York      19651127  141297.0
Florida       19552860  170312.0
Illinois      12882135       NaN

Al igual que las ``Series``, un ``DataFrame`` posee un atributo ``index``:

In [26]:
estados.index[2]

'New York'

Además, tiene un atributo ``columns``, que es un objeto ``Index`` conteniendo las etiquetas de columnas:

In [27]:
estados.columns[1]

'area'

In [28]:
estados['densidad'] = estados['population'] / estados['area']
estados

            population      area    densidad
California    38332521  423967.0   90.413926
Texas         26448193  695662.0   38.018740
New York      19651127  141297.0  139.076746
Florida       19552860  170312.0  114.806121
Illinois      12882135       NaN         NaN

### DataFrame como un diccionario especializado

* De forma similar, podemos pensar al `DataFrame` como un diccionario:
    
    - Un diccionario mapea una key con un valor
    - Un `DataFrame` mapea un nombre de columna con una `Series` de datos.
    
    
* Por ejemplo, pedir el atributo `area` del `DataFrame` `estados` devuelve una `Series`.

In [29]:
estados['area']

California    423967.0
Texas         695662.0
New York      141297.0
Florida       170312.0
Illinois           NaN
Name: area, dtype: float64

### Construyendo objetos `DataFrame`

#### Desde una `Series` simple:

In [30]:
pd.DataFrame(populationn, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### Desde una lista de dicts

In [31]:
# listDicts = [{'hawai': 34}, {'gibraltar': 99}, {'venezuela': 167}, {'kyoto': 3}]
# pd.DataFrame(listDicts)

listComp = [{'a': i, 'b': 1.5 * i}
            for i in range(8)]
#* Lo mismo que hacer: 
#*   listComp = []
#*   for i in range(8):
#*       listComp.append({'a': i, 'b': 1.5 * i})
# listComp

pd.DataFrame(listComp)

   a     b
0  0   0.0
1  1   1.5
2  2   3.0
3  3   4.5
4  4   6.0
5  5   7.5
6  6   9.0
7  7  10.5

* Notar que incluso si alguna key está perdida en el diccionario, Pandas llena con `NaN` el valor:

In [32]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### De un dict de `Series`

In [33]:
pd.DataFrame({'population': populationn,
            'area': area})

            population      area
California    38332521  423967.0
Texas         26448193  695662.0
New York      19651127  141297.0
Florida       19552860  170312.0
Illinois      12882135       NaN

#### Desde un array Numpy de dos dimensiones

In [34]:
numpyA = np.array([[2,4,6], [1,3,5]])
numpyA
pd.DataFrame(numpyA)

   0  1  2
0  2  4  6
1  1  3  5

## El objeto `Index`

* Un `Index` puede ser pensado como un _array inmutable_  o como un set ordenado
* Para ilustrar las implicancias de este punto pensemos en el siguiente ejemplo en el que construimos un `Index` desde una lista de enteros.
* Los `DataFrames` tienen un `Index` que describe a las filas y otro que describe a las columnas.
* Al  `Index` de filas se accede con `df.index` y al de columna `df.columns`.

In [35]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### `Index` como una array inmutable

* Podemos indexar y hacer slicing de forma similar a un array

In [36]:
ind[3]

np.int64(7)

In [37]:
deADos = ind[::3] #saltando de a dos
deAUno = ind[::2] #saltando de a uno
print(deADos)
print(deAUno)

Index([2, 7], dtype='int64')
Index([2, 5, 11], dtype='int64')

Los `Index` tienen atributos similares a los arrays de Numpy

In [38]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

Una diferencia entre los ``Index`` y los arrays de NumPy es que los primeros son *inmutables*:

In [39]:

#! ind[1] = 0 Esto no funciona

### `Index` como un set ordenado

* Se pueden utilizar operaciones de conjuntos con los ``Index`` siguiendo las convenciones de Python

In [40]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [41]:

#* Forma vieja:
# Interseccion = indA & indB
# Union = indA | indB
# Dif_Simetrica = indA ^ indB

Interseccion = indA.intersection(indB)
Union = indA.union(indB)
Dif_Simetrica = indA.symmetric_difference(indB)

print(Interseccion)
print(Union)
print(Dif_Simetrica)

Index([3, 5, 7], dtype='int64')
Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Index([1, 2, 9, 11], dtype='int64')

### Series y DataFrames

In [42]:
import pandas as pd

objMuestra = pd.Series([1,4,5,6,7])
objMuestra

0    1
1    4
2    5
3    6
4    7
dtype: int64

In [43]:
animales = ['Raton', 'Cabra', 'Leon', 'Hormiga']
colores = ['Azul', 'Gris', 'Rojo', 'Amarillo']
#* Los dos tienen que ser del mismo tamaño para hacer una serie.

objJunto = pd.Series(colores, index=animales)
objJunto

Raton          Azul
Cabra          Gris
Leon           Rojo
Hormiga    Amarillo
dtype: str

DataFrames

In [44]:
d = {'tipo_vivienda': ['casa', 'departamento'], 'm2': [35, 49]}
df = pd.DataFrame(data=d)
df

  tipo_vivienda  m2
0          casa  35
1  departamento  49

### Cargando datos

In [ ]:
df = pd.read_csv('fifa-statistics.csv')
df
#! No tenemos el archivo para cargarlo.

FileNotFoundError: [Errno 2] No such file or directory: 'fifa-statistics.csv'

## Selección e Indexing

### loc e iloc

## Análisis descriptivo en Pandas

### describe, info y shape

### unique y value_counts()

### count, min, max, mean, median, std y corr

## Precentiles

Son una medida usada en estadística que indica el valor de la variable por debajo del cual se encuentra un porcentaje dado de observaciones. Ahora los Cuantiles son puntos tomados a intervalos regulares de la función de distribución de una variable aleatoria. Los cuantiles podemos usarlos por grupos que dividan la distribución en partes iguales; obteniendo sus hijos, los Percentiles, Deciles y Quartiles.

### Ordenando datos

### Tablas Dinamicas

## Combinando datasets

### concat y append

### Merge

## Apply y Map

### apply

### applymap

## Missing values

### Filtrando valores faltantes

### Completando valores

### Borrando duplicados